name = "geql_web_app"
version = "1.0.0"
description = "Example web application using GeQL GraphQL library"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
geql = { path = "../../" }
mist = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"