name = "geql_web_app"
version = "1.0.0"
description = "Example web application using GeQL GraphQL library"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
geql = { path = "../../" }
wisp = ">= 2.0.0-rc1 and < 3.0.0"
cake = ">= 2.1.3 and < 3.0.0"
cigogne = ">= 4.0.2 and < 5.0.0"
gleam_json = ">= 3.0.2 and < 4.0.0"
mist = ">= 2.1.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"